// What `cordis.patch.yml` and the generated local overlay wire up.
//
// The patch is YAML the harness reads, not code this package runs, so these
// assertions are on its text. They cover the wiring that fails SILENTLY: a
// roster whose `default` names a directory that is not there resolves to an
// error only when someone opens a session, and a `presets/` directory left out
// of the published `files` list makes the root empty on an installed copy —
// with the shipped modes already disabled by the same patch.

import { test } from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const patch = readFileSync(new URL('../cordis.patch.yml', import.meta.url), 'utf8')
const manifest = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'))

/** Absolute path of one entry in this package. */
function packagePath(relative) {
  return fileURLToPath(new URL(`../${relative}`, import.meta.url))
}

test('turns off the harness prompt sections this agent cannot act on', () => {
  // `harness:identity` (-100) is guarded by one flag on the system-prompt row;
  // `harness:source` (-99) and `app:web-surface` (-98) by one on the web row.
  assert.match(patch, /- id: system-prompt\s*\n\s*config:\s*\n(?:\s*#.*\n)*\s*includeHarnessIdentity: false/)
  assert.match(patch, /surfaceContext: false/)
})

test('restates the web row keys a wholesale config override would drop', () => {
  // A patch REPLACES `config`; dropping these stops the browser opening and
  // the URL line printing, which looks like a broken launcher, not a prompt
  // change.
  const web = /- id: web-runtime\s*\n\s*config:\s*\n((?:\s{4}.*\n|\s*#.*\n)+)/.exec(patch)?.[1] ?? ''
  for (const key of ['openBrowser', 'printUrl', 'trustedHosts']) {
    assert.match(web, new RegExp(`${key}:`), `web-runtime config drops ${key}`)
  }
})

test('disables the shipped roster instead of trying to narrow it', () => {
  // `apps/cli/src/profile-boot.ts` force-overwrites `roots` on the row named
  // `agent-presets` after every patch layer, so narrowing that row is not
  // possible — it has to stop mounting.
  assert.match(patch, /- id: agent-presets\s*\n\s*disabled: true/)
})

test('installs its own roster row, keyed to this package', () => {
  assert.match(patch, /id: dba-agent-presets/)
  assert.match(patch, /name: '@deepseek-ai\/dsh-agent-presets'/)
  assert.match(patch, /'dsh-dba-agent', 'presets'/, 'roots must point at this package')
  assert.match(patch, /includeUserRoot: false/, 'the writable root would reopen the picker')
})

test('the default preset is one this package actually ships', () => {
  const [, id] = /^\s*default: (\S+)\s*$/m.exec(patch) ?? []
  assert.ok(id !== undefined, 'the roster row must name a default preset')

  assert.ok(existsSync(packagePath(`presets/${id}/agent.cordis.yml`)), `presets/${id} has no composition`)
  assert.ok(existsSync(packagePath(`presets/${id}/preset.yml`)), `presets/${id} has no display metadata`)
})

test('the presets directory is published, or the installed roster is empty', () => {
  assert.ok(manifest.files.includes('presets'))
})

// ── the local-debug overlay ──────────────────────────────────────────────────
//
// Generated by the build, so these run against the file the build just wrote.

const localPatchPath = packagePath('cordis.patch.local.yml')

test('the build generates the local-debug overlay', () => {
  assert.ok(existsSync(localPatchPath), 'run `npm run build`')
})

test('the overlay stops every row that would shadow the working tree', () => {
  const local = readFileSync(localPatchPath, 'utf8')
  // Three from an installed copy of this bundle, plus the shipped roster — so
  // the overlay produces the same one-mode picker installed or not.
  for (const id of ['dba-agent', 'dba-skills', 'dba-sql-mcp', 'dba-agent-presets', 'agent-presets']) {
    assert.match(local, new RegExp(`- id: ${id}\\s*\\n\\s*disabled: true`), `${id} stays mounted`)
  }
})

test('the overlay points at files that exist in this tree', () => {
  const local = readFileSync(localPatchPath, 'utf8')
  for (const relative of ['lib/index.js', 'lib/mcp/server.js', 'presets', 'skills']) {
    const absolute = packagePath(relative)
    assert.ok(local.includes(absolute), `the overlay does not name ${relative}`)
    assert.ok(existsSync(absolute), `${relative} is missing from the build`)
  }
})

test('the overlay is not committed — its paths are machine-specific', () => {
  const ignored = readFileSync(packagePath('.gitignore'), 'utf8').split(/\r?\n/)
  assert.ok(ignored.includes('cordis.patch.local.yml'))
})
