// 生成 cordis.patch.local.yml —— 一份给 `--patch` 用的 overlay，路径已替换为字面绝对路径，
// 便于从工作树直接启动，而不必先 `dsh plugin add`：
//
//   node scripts/gen-patch.mjs
//   dsh --profile webtest --patch <repo>/cordis.patch.local.yml --port 7080
//
// 与随包发布的 cordis.patch.yml 内容相同，唯一区别：本包 presets 指向工作树，出货 presets
// 解析成具体路径（loader 只对 config 求值 !!js，这里索性都写死，dev 用完即弃、已 gitignore）。

import { writeFileSync, existsSync, realpathSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join, resolve } from 'node:path'
import { execSync } from 'node:child_process'

const repoPresets = resolve(fileURLToPath(new URL('../presets', import.meta.url)))
const libIndex = resolve(fileURLToPath(new URL('../lib/index.js', import.meta.url)))
const output = resolve(fileURLToPath(new URL('../cordis.patch.local.yml', import.meta.url)))

function resolveShippedPresets() {
  if (process.env.DSH_SHIPPED_PRESETS) return process.env.DSH_SHIPPED_PRESETS
  // 从 dsh 可执行文件反推安装目录：<install>/lib/bin.js → <install>/config/agent-presets
  try {
    const bin = execSync('command -v dsh', { encoding: 'utf8' }).trim()
    const install = dirname(dirname(realpathSync(bin))) // lib/bin.js → 上两级
    const candidate = join(install, 'config', 'agent-presets')
    if (existsSync(candidate)) return candidate
  } catch {}
  return '/usr/local/lib/node_modules/@deepseek-ai/dsh/config/agent-presets'
}

const shippedPresets = resolveShippedPresets()

const content = `# GENERATED by scripts/gen-patch.mjs —— 不要手改，重新运行 npm run build。
# dev overlay：从工作树启动，路径已写死。
#   dsh --profile webtest --patch ${output} --port 7080

- id: agent-presets
  disabled: true

- insert:
    - id: dba-agent-presets
      name: '@deepseek-ai/dsh-agent-presets'
      config:
        default: dba-mode
        includeUserRoot: false
        roots:
          - path: '${repoPresets}'
            trust: system
          - path: '${shippedPresets}'
            trust: system

    # 本包插件（注册 /sql-optimizer 命令）：dev 下用工作树 lib/index.js 的绝对路径。
    - id: dba-command
      name: '${libIndex}'
`

writeFileSync(output, content)
console.log(`generated ${output}`)
console.log(`  dba-mode presets : ${repoPresets}`)
console.log(`  shipped presets  : ${shippedPresets}${existsSync(shippedPresets) ? '' : '  (不存在！用 DSH_SHIPPED_PRESETS 覆盖)'}`)
