// The MySQL dialect: the statements one SQL-optimization walk runs.
//
// Every statement here is read-only and generated by this pack. The statement
// under optimization never appears on its own — only behind EXPLAIN.

import type { EvidenceDialect, EvidenceStep } from '../engine.js'
import type { TableReference } from '../sql.js'

/** MySQL evidence collection. */
export const MYSQL_DIALECT: EvidenceDialect = {
  engine: 'mysql',
  script: 'mysql_query.sh',

  /**
   * Server version, collected before anything else.
   *
   * It is not trivia: it decides which of the recommendations are even
   * available. Hash join, CTEs, window functions, invisible indexes and
   * `EXPLAIN ANALYZE` are 8.0 features, and a rewrite proposed to a 5.7 server
   * that silently assumes them is wrong rather than merely suboptimal.
   * @returns the version step.
   */
  version(): EvidenceStep {
    return { title: '服务器版本', sql: 'SELECT VERSION() AS version, @@sql_mode AS sql_mode;' }
  },

  /**
   * The plan for one statement.
   * @param statement - the normalized statement, without a trailing semicolon.
   * @param analyze - use `EXPLAIN ANALYZE`, which EXECUTES the statement.
   * @returns the plan step.
   */
  explain(statement: string, analyze: boolean): EvidenceStep {
    return {
      title: analyze ? '执行计划（EXPLAIN ANALYZE，已实际执行）' : '执行计划（EXPLAIN FORMAT=JSON）',
      sql: `EXPLAIN ${analyze ? 'ANALYZE ' : 'FORMAT=JSON '}${statement};`,
    }
  },

  /**
   * Structure, indexes and size for one table.
   *
   * All three, because a plan alone does not say whether a full scan is a
   * finding: `Cardinality` decides whether the optimizer would ever pick an
   * index, and `table_rows` decides whether it should.
   * @param table - the table reference, already validated as quotable.
   * @returns the steps for that table.
   */
  tableSteps(table: TableReference): EvidenceStep[] {
    const scope = table.schema === undefined ? 'DATABASE()' : `'${table.schema}'`
    return [
      { title: `${table.quoted} 的建表语句`, sql: `SHOW CREATE TABLE ${table.quoted};` },
      { title: `${table.quoted} 的索引`, sql: `SHOW INDEX FROM ${table.quoted};` },
      {
        title: `${table.quoted} 的规模`,
        sql: 'SELECT table_rows, data_length, index_length, auto_increment, update_time'
          + ` FROM information_schema.tables WHERE table_schema = ${scope}`
          + ` AND table_name = '${table.table}';`,
      },
    ]
  },
}
